package edu.courseproject.server.action;

public enum DAOAction {
    IS_USER_EXISTS,
    FIND_ALL_WORKERS,
    UPDATE_WORKER,
    ADD_WORKER,
    FIND_ALL_CUSTOMERS,
    UPDATE_CUSTOMER,
    ADD_CUSTOMER,
    HAS_POSTED_ORDERS,
    FIND_ALL_PRODUCTS,
    ADD_ORDER,
    CHECK_ORDER,
    UPDATE_ORDER,
    REPORT,
    TOP_CUSTOMER,
    TOP_PRODUCT,
    HISTORY_CUSTOMER,
    HAS_PROCESSED_ORDERS,
    MOVE_FROM_SKLAD,
    FILL_SKLAD
}
